"""
Markdown report converter for EntityRecords.

Produces a structured compliance evidence report grouped by EU AI Act /
GDPR article.  Each section lists the relevant PyTorch entities with a
confidence indicator, lifecycle phase, and docstring excerpt.

WHY MARKDOWN?
    A Markdown file can be committed to Git, reviewed in a pull request,
    rendered on GitHub, and exported to PDF — making it an ideal Art. 11
    (Technical Documentation) artefact that lives alongside the code.

CONFIDENCE INDICATOR
    Each entity heading includes a visual indicator (filled squares):
        ■■■■ high      (≥ 0.8)
        ■■■□ medium    (≥ 0.6)
        ■■□□ low       (≥ 0.4)
        ■□□□ speculative (< 0.4)

OUTPUT
    storage/output/compliance_report.md
"""

from __future__ import annotations

import logging
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

from ..extractors.base import EntityRecord

logger = logging.getLogger("pct.converters.markdown")


# ---------------------------------------------------------------------------
# Article display titles
# ---------------------------------------------------------------------------

# Maps the internal tag name → a human-readable section title.
# Add new regulations here; they will automatically appear in the report.
ARTICLE_TITLES: dict[str, str] = {
    "eu_ai_act_art_9":  "EU AI Act Art. 9 — Risk Management System",
    "eu_ai_act_art_10": "EU AI Act Art. 10 — Data Governance",
    "eu_ai_act_art_11": "EU AI Act Art. 11 — Technical Documentation",
    "eu_ai_act_art_12": "EU AI Act Art. 12 — Record-Keeping & Audit Trail",
    "eu_ai_act_art_13": "EU AI Act Art. 13 — Transparency",
    "eu_ai_act_art_14": "EU AI Act Art. 14 — Human Oversight",
    "eu_ai_act_art_15": "EU AI Act Art. 15 — Accuracy, Robustness & Cybersecurity",
    "eu_ai_act_art_17": "EU AI Act Art. 17 — Quality Management System",
    "eu_ai_act_art_43": "EU AI Act Art. 43 — Conformity Assessment",
    "eu_ai_act_art_61": "EU AI Act Art. 61 — Post-Market Monitoring",
    "eu_ai_act_art_72": "EU AI Act Art. 72 — Serious Incident Reporting",
    "gdpr_art_5":       "GDPR Art. 5 — Principles Relating to Personal Data Processing",
}

# Canonical display order (EU AI Act articles first, then GDPR).
_ARTICLE_ORDER = list(ARTICLE_TITLES.keys())


class MarkdownConverter:
    """Converts EntityRecords to a structured Markdown compliance report."""

    def convert(self, records: list[EntityRecord], output_path: Path) -> None:
        """
        Write a compliance report in Markdown format to *output_path*.

        Parameters
        ----------
        records : list[EntityRecord]
            All entity records to include in the report.
        output_path : Path
            Destination .md file path.
        """
        output_path.parent.mkdir(parents=True, exist_ok=True)

        logger.info(
            "Markdown: building report for %d records → %s",
            len(records), output_path,
        )

        content = self._build_report(records)

        try:
            output_path.write_text(content, encoding="utf-8")
            logger.info("Markdown: done — wrote %s", output_path)
        except OSError as exc:
            logger.error("Markdown: failed to write '%s': %s", output_path, exc)
            raise

    # ------------------------------------------------------------------ #
    # Report construction
    # ------------------------------------------------------------------ #

    def _build_report(self, records: list[EntityRecord]) -> str:
        """Assemble the full Markdown document and return it as a string."""
        lines: list[str] = []

        # ---- Header ----
        generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        lines += [
            "# PyTorch Compliance Evidence Report",
            "",
            "> Automatically generated by the PyTorch Compliance Toolkit.  ",
            f"> Generated at: {generated_at}",
            "",
        ]

        # ---- Summary statistics ----
        tagged = [r for r in records if r.compliance_tags]
        density = len(tagged) / len(records) if records else 0.0
        lines += [
            "## Summary",
            "",
            f"| Metric | Value |",
            f"|--------|-------|",
            f"| Total entities extracted | {len(records):,} |",
            f"| Entities with compliance tags | {len(tagged):,} |",
            f"| Compliance density | {density:.1%} |",
            "",
            "---",
            "",
        ]

        # ---- Per-article sections ----
        # Group records by article tag.
        by_article: dict[str, list[EntityRecord]] = defaultdict(list)
        for rec in records:
            for tag in rec.compliance_tags:
                by_article[tag].append(rec)

        # Split tags into regulatory (eu_ai_act_* / gdpr_*) and technical
        # capability tags so they render in separate named groups.
        regulatory_tags: list[str] = []
        capability_tags: list[str] = []
        for tag in by_article:
            if tag.startswith("eu_ai_act_") or tag.startswith("gdpr_"):
                regulatory_tags.append(tag)
            else:
                capability_tags.append(tag)

        # Sort each group: canonical order first, then any unknown tags.
        regulatory_tags = sorted(
            regulatory_tags,
            key=lambda t: (
                _ARTICLE_ORDER.index(t) if t in _ARTICLE_ORDER else len(_ARTICLE_ORDER)
            ),
        )
        capability_tags = sorted(capability_tags)

        def _render_tag_group(tags: list[str]) -> None:
            nonlocal lines
            for tag in tags:
                article_records = sorted(
                    by_article[tag],
                    key=lambda r: r.mapping_confidence,
                    reverse=True,  # highest confidence first
                )
                # Deduplicate by qualified_name — keep only the highest-confidence
                # record per qualified_name to avoid rendering the same function
                # multiple times (e.g. C++ declarations at different line numbers).
                seen_qnames: set[str] = set()
                deduped_records: list[EntityRecord] = []
                for rec in article_records:
                    qname = rec.qualified_name or ""
                    if qname and qname in seen_qnames:
                        continue
                    if qname:
                        seen_qnames.add(qname)
                    deduped_records.append(rec)
                title = ARTICLE_TITLES.get(tag, tag)
                lines += self._build_article_section(title, tag, deduped_records)

        if regulatory_tags:
            lines += [
                "## Regulatory Evidence",
                "",
                "_Entities mapped to EU AI Act and GDPR articles._",
                "",
            ]
            _render_tag_group(regulatory_tags)

        if capability_tags:
            lines += [
                "## Technical Capability Evidence",
                "",
                "_Entities mapped to internal capability tags "
                "(not direct regulatory articles)._",
                "",
            ]
            _render_tag_group(capability_tags)

        # ---- Footer ----
        lines += [
            "---",
            "",
            "*This report is evidence artefact for EU AI Act Art. 11 "
            "(Technical Documentation) obligations.*",
            "",
        ]

        return "\n".join(lines)

    def _build_article_section(
        self,
        title: str,
        tag: str,
        records: list[EntityRecord],
    ) -> list[str]:
        """Return the Markdown lines for one article section."""
        lines: list[str] = [
            f"## {title}",
            "",
            f"**{len(records)} entities mapped to this article.**  ",
            f"Tag: `{tag}`",
            "",
        ]

        for rec in records:
            lines += self._format_entity(rec)

        lines.append("")
        lines.append("---")
        lines.append("")
        return lines

    def _format_entity(self, rec: EntityRecord) -> list[str]:
        """Return Markdown lines describing one entity."""
        indicator = _confidence_indicator(rec.mapping_confidence)
        lines = [
            f"### `{rec.entity_name}` {indicator}",
            "",
            f"| Field | Value |",
            f"|-------|-------|",
            f"| Type | `{rec.entity_type}` / `{rec.subcategory}` |",
            f"| File | `{rec.source_file}` (line {rec.start_line}) |",
            f"| Lifecycle | `{rec.lifecycle_phase or 'unclassified'}` |",
        ]

        if rec.execution_level:
            lines.append(f"| Execution level | `{rec.execution_level}` |")
        if rec.distributed_safety:
            lines.append(f"| Distributed safety | `{rec.distributed_safety}` |")

        if rec.export_survival:
            survival_str = ", ".join(
                f"{k}={v}" for k, v in rec.export_survival.items()
            )
            lines.append(f"| Export survival | {survival_str} |")

        lines.append(
            f"| Mapping confidence | {rec.mapping_confidence:.2f} |"
        )

        if rec.mapping_rationale:
            lines.append(f"| Evidence | {rec.mapping_rationale} |")

        lines.append("")  # blank line after table

        if rec.docstring:
            excerpt = rec.docstring[:200].replace("\n", " ").strip()
            if len(rec.docstring) > 200:
                excerpt += "…"
            lines += [f"> {excerpt}", ""]

        return lines


# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------


def _confidence_indicator(confidence: float) -> str:
    """Return a visual confidence indicator (filled/empty squares)."""
    if confidence >= 0.8:
        return "■■■■ *high*"
    elif confidence >= 0.6:
        return "■■■□ *medium*"
    elif confidence >= 0.4:
        return "■■□□ *low*"
    else:
        return "■□□□ *speculative*"
